### ISSUE TITLE
Regarding mod performance issues.

### ISSUE THREAD

**Issue by EmptyDreams** [CesiumMC/cesium-fabric#10]
I noticed that in your mod description, it states: "all data to disk after each server tick." I'm concerned that this action might increase the load on the server's hard drive and potentially make other optimization mods related to chunk saving ineffective. Could you please address my concerns? What benefits would using this mod bring to the server, and what might I lose? Is there a necessity to use this mod on the server?

**Comment by yamayaki1** [comment]
Hello,

I, personally, have not seen any real difference in the load put on the hard drive while using this mod compared to vanilla. Because this mod uses better compression on chunk data, the load put on the drive should technically be lower.

As of now I have only tested compatibility with C2ME. Any newer chunk loading optimisation mod might be incompatible because of the way Cesium replaces the chunk writing/ reading logic. Apart from that, other non-chunk-optimisation mods should work just as fine.

The biggest advantage as of right now is the better compression of chunk data. Downsides are incompatibilities with mods like BlueMap and similar, that have to access chunk files directly to render online accessible versions of the map.

You are free to use or not use this mod as **you** like :)
