### ISSUE TITLE
Port to older versions of Minecraft

### ISSUE THREAD

**Issue by Dann50** [CesiumMC/cesium-fabric#17]
Any plans on porting 0.2.4 to 1.20.1?

**Comment by yamayaki1** [comment]
Shouldn't be too hard. I might look into that this weekend.

**Comment by yamayaki1** [comment]
Most parts of the mod I was able to back-port without problems but the GUI is still nonfunctional. And because of how frail the code for GUIs before 1.20.2 is, this will still take some time. I'd like to do this proper this time, unlike previous versions.

If everything goes well I can maybe publish a build the next two days.

**Comment by AlexanderwithaA** [comment]
Would porting to 1.20.4 as well be easily done?

**Comment by yamayaki1** [comment]
> Would porting to 1.20.4 as well be easily done?

Probably. But I don’t have much time except this upcoming weekend.

The 1.20.1 port is very close to being done (some cleanups and testing), so I can work on that after that.

**Comment by yamayaki1** [comment]
I just published a pre-release for Cesium on GitHub that also targets the versions 1.20.1 and 1.20.4. Once Mojang releases 1.21.2 I will do a proper release on modrinth and close this issue.

**Comment by AlexanderwithaA** [comment]
I just had a thought, will there be any issue updating older 1.20.1/1.20.4 worlds To the new version?

**Comment by yamayaki1** [comment]
> I just had a thought, will there be any issue updating older 1.20.1/1.20.4 worlds To the new version?

Cesium's data format hasn't really changed during the last versions, so newer versions of this mod can read worlds from older versions just fine.

Opening a world from `MC 1.19.4 (Cesium 0.1.4) -> MC 1.20.1 (Cesium 0.1.4) -> MC 1.20.1 (Cesium 0.2.5)` confirms this.

And any 0.2.5 release is compatible with each other, because they share the same code base.
